# Generated by Django 2.0.1 on 2018-01-22 20:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('menus', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='item',
            options={'ordering': ['-updated', '-timestamp']},
        ),
        migrations.RenameField(
            model_name='item',
            old_name='content',
            new_name='contents',
        ),
    ]
